title: Knowledge Sharing
description: A Simple Blog by redqx
author: Den9Qux1ang
github: https://github.com/i1oveyou
about: I am a mobile security research engineer at NowSecure. Also, independent contractor evaluating mobile payments, DRM, whitebox crypto, video-games, malware, embedded devices and all related with software security. Based in Europe/UK/US
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "https://twitter.com/enovella_"
    # - icon: fa-linkedin
    #   link: "https://www.linkedin.com/in/eduardo-novella-3b808260/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/i1oveyou"

share:
  twitter_username: resmilere441915
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://enovella.i1oveyou.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
